version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV
      - MARIADB_HOS
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - DATABASE_URL
      - REDIS_URL
      - APP_SECRET
    networks:
      - mynetwork
    links:
      - crispy-octo-mariadb:mariadb.host
      - "redis:redis.host"
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bundle exec rake environment resque:work QUEUE=*
    restart: always
    links:
      - "redis:redis.host"
    ports:
      - 3001:3001
    environment:
      - RAILS_ENV
      - QUEUE=*
      - MARIADB_HOS
      - MARIADB_PORT
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
      - DATABASE_URL
      - REDIS_URL
      - APP_SECRET
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379

  crispy-octo-mariadb:
    image: "mariadb:10.6"
    container_name: crispy-octo-mariadb
    volumes:
        - "._mysql_data_dir/:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MARIADB_ROOT_PASSWORD=pass
      - MARIADB_DATABASE
    ports:
      - 3306:3306
    networks:
      - mynetwork

networks:
  mynetwork:

